In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("ENB.csv")
X=dataset.iloc[:,:-2].values
y=dataset.iloc[:,8:10].values

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [25]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [27]:
print(np.concatenate((y_test,regressor.predict(X_test)),axis=1))

[[15.18 17.63 15.16 17.04]
 [10.32 13.57 10.46 13.72]
 [37.26 34.62 35.65 41.07]
 [16.95 21.16 17.41 21.46]
 [32.26 33.34 32.69 33.24]
 [27.9  34.2  28.83 29.36]
 [28.18 30.18 28.15 30.19]
 [28.95 30.34 29.22 31.71]
 [29.07 29.82 28.4  34.52]
 [23.8  24.61 24.37 25.11]
 [ 6.4  11.67  6.37 11.29]
 [42.5  38.35 42.74 38.84]
 [11.22 14.65 11.34 14.81]
 [43.1  39.41 42.62 39.07]
 [41.96 37.7  41.09 47.01]
 [26.33 31.06 25.37 31.76]
 [10.7  13.87 10.68 14.21]
 [28.09 34.33 29.14 29.58]
 [14.65 15.38 13.99 14.35]
 [12.29 15.4  12.49 15.09]
 [12.46 14.38 12.87 15.85]
 [32.71 33.13 32.69 33.24]
 [10.77 14.14 10.64 13.67]
 [38.57 43.86 38.67 43.8 ]
 [ 6.04 11.17  6.01 10.94]
 [14.66 17.37 14.71 17.01]
 [13.   14.47 13.   14.28]
 [14.41 16.69 14.19 16.62]
 [10.75 14.27 10.68 14.21]
 [39.89 37.54 40.   36.26]
 [12.74 13.97 12.59 14.24]
 [12.74 16.14 12.84 16.26]
 [41.26 46.44 42.77 38.33]
 [12.77 16.22 13.   15.87]
 [28.56 29.78 28.57 29.69]
 [35.99 36.07 36.95 36.87]
 [13.97 16.08 14.07 16.11]
 

In [29]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9635886752589126