In [21]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [23]:
dataset=pd.read_csv("ENB.csv")
X=dataset.iloc[:,:-2].values
y=dataset.iloc[:,8:10].values

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [29]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [31]:
print(np.concatenate((y_test,regressor.predict(X_test)),axis=1))

[[15.18       17.63       17.41297959 19.2009987 ]
 [10.32       13.57        8.00982785 12.26265593]
 [37.26       34.62       29.43547632 32.24949452]
 [16.95       21.16       25.82883064 29.77653556]
 [32.26       33.34       31.09158148 32.08738475]
 [27.9        34.2        27.45520882 30.21690103]
 [28.18       30.18       28.25886363 29.99445773]
 [28.95       30.34       34.11385766 35.56416236]
 [29.07       29.82       29.377148   32.04744936]
 [23.8        24.61       28.49020749 31.09157711]
 [ 6.4        11.67        6.97411216 11.91386715]
 [42.5        38.35       35.19788541 36.88921201]
 [11.22       14.65       11.76843665 14.87177905]
 [43.1        39.41       35.37842988 36.76961305]
 [41.96       37.7        35.85738497 36.84091298]
 [26.33       31.06       26.58621569 29.66779114]
 [10.7        13.87        9.43405177 13.49187326]
 [28.09       34.33       27.29555712 30.19313439]
 [14.65       15.38       15.97681642 18.0787433 ]
 [12.29       15.4        12.28

In [33]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8973910776048324