In [15]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

In [17]:
dataset=pd.read_csv("ENB.csv")
X=dataset.iloc[:,:-2].values
y=dataset.iloc[:,8:10].values

In [19]:
print(X)

[[9.800e-01 5.145e+02 2.940e+02 ... 2.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 3.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 4.000e+00 0.000e+00 0.000e+00]
 ...
 [6.200e-01 8.085e+02 3.675e+02 ... 3.000e+00 4.000e-01 5.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 4.000e+00 4.000e-01 5.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 4.000e-01 5.000e+00]]


In [21]:
print(y)

[[15.55 21.33]
 [15.55 21.33]
 [15.55 21.33]
 ...
 [16.44 17.11]
 [16.48 16.61]
 [16.64 16.03]]


In [23]:
dataset.isnull().sum()

X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
X7    0
X8    0
Y1    0
Y2    0
dtype: int64

In [35]:
from sklearn.preprocessing import PolynomialFeatures
PF_regressor=PolynomialFeatures(degree=2)
X_poly=PF_regressor.fit_transform(X)

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_poly,y,test_size=0.2,random_state=0)

In [66]:
from sklearn.linear_model import LinearRegression
poly_regressor=LinearRegression()
poly_regressor.fit(X_train,y_train)
y_pred=poly_regressor.predict(X_test)

In [68]:
np.set_printoptions(precision=2)

In [70]:
result=np.concatenate((y_test,poly_regressor.predict(X_test)),axis=1)

In [72]:
print(result)

[[15.18 17.63 15.21 17.29]
 [10.32 13.57 10.27 13.28]
 [37.26 34.62 35.87 38.12]
 [16.95 21.16 17.88 23.07]
 [32.26 33.34 32.55 32.94]
 [27.9  34.2  27.79 31.07]
 [28.18 30.18 28.59 29.45]
 [28.95 30.34 29.31 30.62]
 [29.07 29.82 29.51 32.33]
 [23.8  24.61 23.47 25.82]
 [ 6.4  11.67  6.21 11.81]
 [42.5  38.35 42.06 43.29]
 [11.22 14.65 11.38 14.52]
 [43.1  39.41 42.29 43.  ]
 [41.96 37.7  41.13 42.35]
 [26.33 31.06 26.46 29.1 ]
 [10.7  13.87 10.58 14.12]
 [28.09 34.33 26.97 30.72]
 [14.65 15.38 15.11 15.87]
 [12.29 15.4  12.93 15.33]
 [12.46 14.38 13.42 15.53]
 [32.71 33.13 32.82 32.97]
 [10.77 14.14 10.66 13.85]
 [38.57 43.86 39.53 40.88]
 [ 6.04 11.17  6.14 11.49]
 [14.66 17.37 14.59 16.72]
 [13.   14.47 13.07 14.37]
 [14.41 16.69 12.88 15.83]
 [10.75 14.27  9.62 13.73]
 [39.89 37.54 39.13 40.51]
 [12.74 13.97 12.81 13.87]
 [12.74 16.14 13.79 16.14]
 [41.26 46.44 42.16 42.88]
 [12.77 16.22 13.74 16.17]
 [28.56 29.78 28.89 29.48]
 [35.99 36.07 36.83 37.14]
 [13.97 16.08 14.2  16.49]
 

In [74]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9801369959328285